cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: xxx.xxx@gmail.com
      name: admin
      password: $2b$12$4BSoCNmlPUJ8Al4O00UWkubIZ.nZCciIT711hdS.5leUuLpXMPWvO
preauthorized:
  emails:
  - xxx.xxx@gmail.com
