cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: suengjae.hong@gmail.com
      name: admin
      password: $2b$12$4BSoCNmlPUJ8Al4O00UWkubIZ.nZCciIT711hdS.5leUuLpXMPWvO
    mike424:
      email: suengjae.hong@gmail.com
      name: suengj
      password: $2b$12$Yo95iZJV3Pm/3uHBuEFu3egZXQbmxrakLgY5lM5hTmCgdKanvWU3q
preauthorized:
  emails:
  - suengjae.hong@gmail.com
